export const BOOKS_LIST_REQUEST = 'BOOKS_LIST_REQUEST'
export const BOOKS_LIST_SUCCESS = 'BOOKS_LIST_SUCCESS'
export const BOOKS_LIST_FAIL = 'BOOKS_LIST_FAIL'

export const BOOK_REQUEST = 'BOOK_REQUEST'
export const BOOK_SUCCESS = 'BOOK_SUCCESS'
export const BOOK_FAIL = 'BOOK_FAIL'

export const BOOK_DELETE_REQUEST = 'BOOK_DELETE_REQUEST'
export const BOOK_DELETE_SUCCESS = 'BOOK_DELETE_SUCCESS'
export const BOOK_DELETE_FAIL = 'BOOK_DELETE_FAIL'

export const BOOK_CREATE_REQUEST = 'BOOK_CREATE_REQUEST'
export const BOOK_CREATE_SUCCESS = 'BOOK_CREATE_SUCCESS'
export const BOOK_CREATE_FAIL = 'BOOK_CREATE_FAIL'
export const BOOK_CREATE_RESET = 'BOOK_CREATE_RESET'

export const BOOK_UPDATE_REQUEST = 'BOOK_UPDATE_REQUEST'
export const BOOK_UPDATE_SUCCESS = 'BOOK_UPDATE_SUCCESS'
export const BOOK_UPDATE_FAIL = 'BOOK_UPDATE_FAIL'
export const BOOK_UPDATE_RESET = 'BOOK_UPDATE_RESET'